In [1]:
# STEP 1: IMPORT LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
# STEP 2: LOAD DATASET
dataset = pd.read_csv("student.csv")
print(dataset.head())  # Optional: view top 5 rows

   StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723   
1       1002   18       0          0                  1        15.408756   
2       1003   15       0          2                  3         4.210570   
3       1004   17       1          0                  3        10.028829   
4       1005   17       1          0                  2         4.672495   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1   
1         0         0                1                0       0      0   
2        26         0                2                0       0      0   
3        14         0                3                1       0      0   
4        17         1                3                0       0      0   

   Volunteering       GPA  GradeClass  
0             0  2.929196         2.0  
1             0  3

In [3]:
# STEP 3: Input-output label separation
# Using StudentID only as feature (you can change this if more features are relevant)
x = dataset[["StudentID"]].values  # Feature (X)
y = dataset["GradeClass"].values   # Target label (y) as 1D array

In [4]:
# STEP 4: Train-test split
# 30% TESTING, 70% TRAINING
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [5]:
# STEP 5: Feature Scaling
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [6]:
# STEP 6: Train the KNN classifier
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [8]:
# STEP 7: Make Predictions
y_predict = classifier.predict(x_test)

In [9]:
# STEP 8: Evaluate the model
print("Confusion Matrix:\n", confusion_matrix(y_test, y_predict))
print("\nClassification Report:\n", classification_report(y_test, y_predict))
print("Accuracy Score:", accuracy_score(y_test, y_predict))

Confusion Matrix:
 [[  3  12   4   1  13]
 [ 10  11  14   6  39]
 [ 16  20  20   6  59]
 [ 13  22  18   7  67]
 [ 24  59  48  21 205]]

Classification Report:
               precision    recall  f1-score   support

         0.0       0.05      0.09      0.06        33
         1.0       0.09      0.14      0.11        80
         2.0       0.19      0.17      0.18       121
         3.0       0.17      0.06      0.08       127
         4.0       0.54      0.57      0.55       357

    accuracy                           0.34       718
   macro avg       0.21      0.20      0.20       718
weighted avg       0.34      0.34      0.33       718

Accuracy Score: 0.3426183844011142
