In [2]:
IMPORT LIBRARIES

In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
LOAD DATASET

In [44]:
dataset = pd.read_csv("student.csv")
dataset.head()

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723   
1       1002   18       0          0                  1        15.408756   
2       1003   15       0          2                  3         4.210570   
3       1004   17       1          0                  3        10.028829   
4       1005   17       1          0                  2         4.672495   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1   
1         0         0                1                0       0      0   
2        26         0                2                0       0      0   
3        14         0                3                1       0      0   
4        17         1                3                0       0      0   

   Volunteering       GPA  GradeClass  
0             0  2.929196         2.0  
1             0  3.042915         1.0  
2             0  0.112602         4.0  
3             0  2.054218         3.0  
4             0  1.288061         4.0

In [ ]:
input output label seperation

In [45]:
x=dataset[["StudentID"]].values
y=dataset[["GradeClass"]].values

print(x)

[[1001]
 [1002]
 [1003]
 ...
 [3390]
 [3391]
 [3392]]


In [ ]:
train & test & spilit

In [46]:
# 4O % TESTING 60% TRAINING
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
trainfit

In [47]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [40]:
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train,y_train)


D:\anaconda installation\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [ ]:
#trainpredict

In [50]:
y_predict = classifier.predict(x_test)

In [ ]:
#accuracy measure score

In [51]:
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))
print("Accuracy:", accuracy_score(y_test, y_predict))

[[  4  10   5   4  21]
 [ 11  14  18   9  54]
 [ 15  31  22  12  77]
 [ 11  28  27  13  87]
 [ 27  70  69  29 289]]
              precision    recall  f1-score   support

         0.0       0.06      0.09      0.07        44
         1.0       0.09      0.13      0.11       106
         2.0       0.16      0.14      0.15       157
         3.0       0.19      0.08      0.11       166
         4.0       0.55      0.60      0.57       484

    accuracy                           0.36       957
   macro avg       0.21      0.21      0.20       957
weighted avg       0.35      0.36      0.35       957

Accuracy: 0.3573667711598746
