In [13]:
# STEP 1: IMPORT LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

In [14]:
# STEP 2: LOAD DATASET
dataset = pd.read_csv("student.csv")
print(dataset.head())  # Optional: view top 5 rows

   StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723   
1       1002   18       0          0                  1        15.408756   
2       1003   15       0          2                  3         4.210570   
3       1004   17       1          0                  3        10.028829   
4       1005   17       1          0                  2         4.672495   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1   
1         0         0                1                0       0      0   
2        26         0                2                0       0      0   
3        14         0                3                1       0      0   
4        17         1                3                0       0      0   

   Volunteering       GPA  GradeClass  
0             0  2.929196         2.0  
1             0  3

In [15]:
# STEP 3: Input-output label separation
# Using StudentID only as feature (you can change this if more features are relevant)
x = dataset[["StudentID"]].values  # Feature (X)
y = dataset["GradeClass"].values   # Target label (y) as 1D array

In [16]:
# STEP 4: Train-test split
# 30% TESTING, 70% TRAINING
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [17]:
# STEP 5: Feature Scaling
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [18]:
# STEP 6: Train the Naive Bayes
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [19]:
# STEP 7: Make Predictions
y_predict = classifier.predict(x_test)

In [20]:
# STEP 8: EVALUATION
print("Confusion Matrix:\n", confusion_matrix(y_test, y_predict))
print("\nClassification Report:\n", classification_report(y_test, y_predict))
print("Accuracy Score:", accuracy_score(y_test, y_predict))
print("F1 Score:", f1_score(y_test, y_predict, average='weighted'))

Confusion Matrix:
 [[  0   0   0   0  33]
 [  0   0   0   0  80]
 [  0   0   0   0 121]
 [  0   0   0   0 127]
 [  0   0   0   0 357]]

Classification Report:
               precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        33
         1.0       0.00      0.00      0.00        80
         2.0       0.00      0.00      0.00       121
         3.0       0.00      0.00      0.00       127
         4.0       0.50      1.00      0.66       357

    accuracy                           0.50       718
   macro avg       0.10      0.20      0.13       718
weighted avg       0.25      0.50      0.33       718

Accuracy Score: 0.4972144846796657
F1 Score: 0.3302429228477035


D:\anaconda installation\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda installation\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda installation\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
